-- Full Auto snapshots need a "use case" dimension: the admin has actually
-- been entering use-case-specific data all along (e.g. one row for Deposit/
-- withdrawal, another for a different use case), not one aggregate row per
-- date. Adds a free-text use_case column, defaulting existing + future
-- "whole operator" rows to 'Overall', and widens the uniqueness constraint
-- so a date can have one row per use case instead of just one row total.

alter table public.operator_automation_snapshots
  add column if not exists use_case text not null default 'Overall';

-- Drop whatever unique constraint currently exists on (operator_id,
-- snapshot_date) -- looked up dynamically rather than by a guessed
-- autogenerated name, since this project's migration history has had drift
-- before and the name isn't guaranteed.
do $$
declare
  c record;
begin
  for c in
    select conname from pg_constraint
    where conrelid = 'public.operator_automation_snapshots'::regclass
      and contype = 'u'
  loop
    execute format('alter table public.operator_automation_snapshots drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.operator_automation_snapshots
  add constraint operator_automation_snapshots_operator_date_usecase_key
  unique (operator_id, snapshot_date, use_case);
